# Generated by scripts/bootstrap-backend.sh --env dev
# Fill in storage_account_name after running the bootstrap script.
terraform {
  backend "azurerm" {
    resource_group_name  = "pm-tfstate-rg"
    storage_account_name = "pmtfstatedev"   # created by bootstrap-backend.sh
    container_name       = "tfstate"
    key                  = "dev.terraform.tfstate"
    use_oidc             = true
  }
}
